language: ruby

env:
  - TEST_CXX=1 TEST_NODE=1
  - TEST_CXX=1 SUDO=1
  - TEST_RUBY=1 TEST_RUBY_VERSION=1.9.3 TEST_USH=1
  - TEST_NGINX=1 TEST_STANDALONE=1
  - TEST_APACHE2=1
  - TEST_SOURCE_PACKAGING=1

before_install:
  - 'gem update --system 2.6.4 && gem install bundler'
  - 'gem --version'
  - 'bundle --version'
  - 'rvm list'

install: "true"
script: ./dev/ci/run_travis.sh

cache:
  directories:
    - cache

notifications:
  slack: phusionnl:PH5p7JYXyv2XLDpICHh8Nj6F

os:
  - osx
  - linux

