language: ruby

env:
  - TEST_FULL_COMPILE=1
  - TEST_COMPILE_NGINX=1
  - TEST_CXX=1
  - TEST_RUBY=1 TEST_RUBY_VERSION=1.8.7
  - TEST_RUBY=1 TEST_RUBY_VERSION=1.9.3

before_install:
  - sudo apt-get install apache2-mpm-worker apache2-threaded-dev
  - cp test/config.json.travis test/config.json

script: ./dev/run_travis.sh
